namespace :pi do
  task :deploy, :ssh_user do |t, args|
    ssh_user = args[:ssh_user]
    remote_server = "192.168.1.121"
    remote_root = "~/printer_driver/"
    rsync = "rsync -avz --delete ./ #{ssh_user}@#{remote_server}:#{remote_root}"
    puts rsync
    system(rsync)
    puts "*** DONE! ***"
  end
end
